### ISSUE TITLE
致命错误: Class 'Config' not found

### ISSUE THREAD

**Issue by sickeeer** [czewail/think-api#1]
in /website/tp5/vendor/zewail/think-api/src/Response/Factory.php line 25

**Comment by czewail** [comment]
是5.1版本吗

**Comment by sickeeer** [comment]
composer 安的   
v 5.0.11

**Comment by sickeeer** [comment]
所以..5.1 命名空间已经不用think了？ 新增了 pull方法？ 我一脸懵逼.. 讲真是 基于api 友好这个概念 从YII来参观的.. 然鹅，竟然在文档里没看到rbac、oauth2、jwt这些..哪里友好了.. 就输出json么....

**Comment by czewail** [comment]
5.1 用了Facade的别名 原来think命名空间下的类的静态方法都换成了动态方法，然后用门面静态调用，至于其它的。。。只有一些基本类库，第三方慢慢集成吧。

**Comment by czewail** [comment]
另外，基于这个包 topthink/think:5.1.*-dev 测试了 没有问题

**Comment by sickeeer** [comment]
走通了，谢谢。 就是trait有点鸡肋
