### ISSUE TITLE
语法错误: unexpected 'array' (T_ARRAY), expecting identifier (T_STRING)

### ISSUE THREAD

**Issue by sofwu** [czewail/think-api#11]
Factory.php line 113

    /**
     * 数组的响应
     *
     * @param  array
     * @return Zewail\Api\Http\Response
     */
    public function array(array $content = null)
    {
        return new Response($content);
    }

**Comment by czewail** [comment]
只支持数组传入

**Comment by sofwu** [comment]
@czewail 是函数命名的问题吧，array是内置函数

**Comment by czewail** [comment]
这是对象方法，和函数没关系。。。参数加了类型限制，只能传入数组

**Comment by sofwu** [comment]
我试过了传了数组进去还是报错，我改了这个命名就没事了

**Comment by czewail** [comment]
你贴调用代码

**Comment by sofwu** [comment]
return $this->response->array(['token'=> 'token']);

**Comment by czewail** [comment]
```php
use Zewail\Api\Api;

class News
{
	use Api;

	public function index()
	{
		return $this->response->array([]);
	}
}
```

**Comment by sofwu** [comment]
@czewail 
不是直接继承基本控制器吗？

use think\Controller;
use Zewail\Api\Api;

class BaseController extends Controller
{
    use Api;
}

////////////////////////////////////////////
use app\index\model\Users;
use think\facade\Validate;
use think\Request;

class User extends BaseController{

    public function login(Request $request= null){ //用户登录

        return $this->response->array(['token'=> 'token']);
    }
}

**Comment by czewail** [comment]
我这边全部新下载。。然后也是这样的代码。没问题。。。
