### ISSUE TITLE
接管异常在windows不能使用

### ISSUE THREAD

**Issue by sofwu** [czewail/think-api#12]
'exception_handle' => 'Zewail\Api\Exceptions\handleException',

**Comment by czewail** [comment]
接管了TP的 Response Exception 其他代码之类的异常由TP处理

**Comment by sofwu** [comment]
Class 'Zewail\Api\Exceptions\handleException' not found

**Comment by sofwu** [comment]
5.1版本默认的目录规范是小写，类文件命名是驼峰法，并且首字母大写。 现在目录还是大写开头的
