### ISSUE TITLE
方法不存在:think\Request->instance

### ISSUE THREAD

**Issue by KingyoWang** [czewail/think-api#13]
在ThinkPHP V5.1.7 下，报下面这个错误。

方法不存在:think\Request->instance

Zewail\Api\JWT\Factories\Payload 第37行
 $this->request = Request::instance();  导致的。

**Comment by czewail** [comment]
[bae24519d3f471e7df7b45f07e53984059572de3](https://github.com/czewail/think-api/commit/bae24519d3f471e7df7b45f07e53984059572de3)
