### ISSUE TITLE
jwtEncrypt 方法逻辑有点问题，我的是加盐的

### ISSUE THREAD

**Issue by indiboy** [czewail/think-api#15]
jwtEncrypt 方法逻辑有点问题，我的是加盐的，每个人加的盐还不一样，盐是salt，是user表其中的一个字段。建议jwtEncrypt直接把$credentials传进去再处理

/vendor/zewail/think-api/src/JWT/Factory.php

$inputPwd = $userModel->jwtEncrypt($credentials[$pwdField]);
修改为
$inputPwd = $userModel->jwtEncrypt($credentials,$user);

**Comment by czewail** [comment]
添加参数
[f103d89](https://github.com/czewail/think-api/commit/f103d896bba857bc6e569e9a50eb5a2ebdaf4ea6)

PS： 建议提交Pull Request😊😊😊
