### ISSUE TITLE
ResponseException

### ISSUE THREAD

**Issue by diaolingzc** [czewail/think-api#17]
根据文档修改：
`'exception_handle'       => 'Zewail\Api\Exceptions\handleException',`
`return ResponseException`http状态码异常，会返回`exception_tmpl`响应。

而非 `namespace Zewail\Api\Http\Response`类里面继承的`think\response\Json`，
想咨询下您这里需要怎么输出json，而非thinphp自定义的异常页面模板`exception_tmpl`输出（通常情况下，这种输出对api开发来说是没有意义的）。

thinkphp版本 V5.1.17。

感谢并期待您的回复。tks

**Comment by czewail** [comment]
@diaolingzc `throw new ResponseException($statusCode, $message)`

**Comment by diaolingzc** [comment]
感谢您的回复。这边具体代码如下：
config.php
```php
'app_debug'              => false,
'show_error_msg'         => false,
'exception_handle'       => 'Zewail\Api\Exceptions\handleException',
```

app\api\model\Users.php

```php
<?php
namespace app\api\model;
use Zewail\Api\Exceptions\ResponseException;
class Users
{
	public function store()
	{
		$re = [
			'a' => 1,
			'b' => 2
		];
		throw new ResponseException(404, json_encode($re));
	}
}
```

app\api\controller\v1\User.php
```php
<?php
namespace app\api\controller\v1;
use app\api\model\Users;

use Zewail\Api\Facades\Response as ApiResponse;

class User{

	public function store(Users $user)
	{
		$user->store();
	}
}
```

route\api.php
```php
<?php
use Zewail\Api\Facades\ApiRoute;

ApiRoute::version('v1', function(){
    Route::get('users/store', 'api/V1.User/store');
});
```

测试结果如截图：
![image](https://user-images.githubusercontent.com/21998370/41888990-c300894c-793a-11e8-8753-af603d28df16.png)

如果`config.php`中`app_debug = true`，结果如下：
![image](https://user-images.githubusercontent.com/21998370/41889037-eb2c9e60-793a-11e8-9a17-7d7f5429b4a1.png)

如果`config.php`中`'app_debug' => true,'show_error_msg' => true`，结果如下：
![image](https://user-images.githubusercontent.com/21998370/41889067-1525bdd2-793b-11e8-84e9-96709464a62a.png)

初衷是在model的业务逻辑中，出现异常则直接response http status_code 及 json 格式的 message

thinkphp版本 V5.1.17。

感谢并期待您的回复。tks

**Comment by diaolingzc** [comment]
已根据源码找到解决方案：
```php
$response = Response::create($result, $type, $code)->header($header);
throw new HttpResponseException($response);
```

**Comment by czewail** [comment]
@diaolingzc 非常感谢您提供的测试结果与解决方案，最近比较忙，可能与TP新版本的异常修改有关，我抽时间看下，如果可以的话，您可以提交相关PR合并
再次感谢

**Comment by czewail** [comment]
@diaolingzc 请问该版本 `return ApiResponse::error('错误信息', 404);` 这些内置错误方法，返回的是不是正常
因为我在出差，暂时没法测试，期待测试结果

**Comment by diaolingzc** [comment]
测试结果如下：
app.php
```php
'app_debug'              => false,
'show_error_msg'         => false,
'exception_handle'       => '',
```
route未做变动。

app\api\controller\v1\User.php
```php
<?php
namespace app\api\controller\v1;
//use app\api\model\Users;

use Zewail\Api\Facades\Response as ApiResponse;

class User{

	public function store(Users $user)
	{
		return ApiResponse::error('错误信息', 404);
	}
}
```

结果如下：
![image](https://user-images.githubusercontent.com/21998370/41949494-365844ac-79f4-11e8-8ede-514f5e728b55.png)

修改app.php
```php
'exception_handle'       => 'Zewail\Api\Exceptions\handleException',
```
结果如下：
![image](https://user-images.githubusercontent.com/21998370/41949537-64e895f6-79f4-11e8-95fb-10cb334bc0a2.png)

会自动使用异常页面模板exception_tmpl输出，而非自定义json。
