### ISSUE TITLE
响应过滤器求添加方法

### ISSUE THREAD

**Issue by robin-dongbin** [czewail/think-api#2]
现在的过滤方法是这样的，`return ApiResponse::item($user, ['id', 'name', 'age']);`。能不能添加两个方法，only和except,可以实现`ApiResponse::item($user)->only('id','name')`这样的调用方式，另外既然继承了TP的响应类，为什么要把header，eTag之类的方法重写一遍？

**Comment by czewail** [comment]
可以，下班后我添加一下

**Comment by czewail** [comment]
已更新
