### ISSUE TITLE
另外建议响应里加一个success方法用来返回成功消息

### ISSUE THREAD

**Issue by robin-dongbin** [czewail/think-api#3]
我就不fork了自己写啦

**Comment by robin-dongbin** [comment]
重新思考了一下，简单来说就是感觉目前的成功返回只针对了get请求的返回，就是不同格式的成功返回，并没有针对put，post，delete之类的成功返回处理方法，可以参考[](http://blog.csdn.net/fred_lzy/article/details/51629232)这篇文章

**Comment by robin-dongbin** [comment]
http://blog.csdn.net/fred_lzy/article/details/51629232

**Comment by czewail** [comment]
好的，我一起更新

**Comment by XinJiangQingMang** [comment]
已入坑

**Comment by czewail** [comment]
已更新
