### ISSUE TITLE
这个例子跑不起来呢   

### ISSUE THREAD

**Issue by XinJiangQingMang** [czewail/think-api#4]
当然，也可以使用门面(Facade)来获取

namespace app\index\controller;

use Zewail\Api\Facades\Response as ApiResponse;

class IndexController
{
	public function index() {
        return ApiResponse::array([]);
    }
}

致命错误: Class 'Zewail\APi\Facades\Response' not found

**Comment by czewail** [comment]
tp 是5.1的吗

**Comment by robin-dongbin** [comment]
这个例子没问题。
这个例子才有问题：
```
ApiRoute::version('v2', function () {
    Route::rule('new/:id','index/V2/News/read');
});
```

`'index/V2/News/read'`这种写法确定能解析？

**Comment by czewail** [comment]
需要新建V2文件夹

**Comment by robin-dongbin** [comment]
我知道，但是这种目录结构是解析不了的,要解析得写成`index/v2.News/read`这种写法，我试过了默认配置是不能解析的，难道你改了TP的配置？另外能发下你的目录结构？

**Comment by czewail** [comment]
命名空间也要加V2

**Comment by winter-ice** [comment]
加了。。

**Comment by robin-dongbin** [comment]
求个应用目录结构，我看下。。可能我结构有问题

**Comment by czewail** [comment]
刚看了下，应该用完整的命名空间，例如：
```php
Route::rule('new/:id','app\index\controller\V2\News@read');
```

**Comment by robin-dongbin** [comment]
`index/v2.News/read`这种写法也是可以的

**Comment by czewail** [comment]
恩，测试了，是可以的，文档已更新

**Comment by XinJiangQingMang** [comment]
这个例子 如果你是引用的话 命名空间大小写问题导致的报错  src/facades/Response.php 的命名空间   namespace Zewail\APi\Facades;   应该是 namespace Zewail\Api\Facades;  所以引用报错   @czewail
